# -*- coding: utf-8 -*-
"""FinancialMarketSimulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f0GlU0OveeMNyUAOdVN7a4UHFyzbPjg8

//start
"""

import yfinance as yf

df = yf.download("^NSEI", start="2018-01-01")

print(df.head())

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import yfinance as yf

df = yf.download("^NSEI", start="2018-01-01")

print(df.head())

import numpy as np

def brownian_motion(T, N):
    dt = T / N


    dW = np.random.normal(0, np.sqrt(dt), size=N)
    W = np.insert(np.cumsum(dW), 0, 0)

    return W

def simulate_gbm(S0, mu, sigma, T, N):
    dt = T / N

    dW = np.random.normal(0, np.sqrt(dt), size=N)
    W = np.insert(np.cumsum(dW), 0, 0)

    t = np.linspace(0, T, N+1)

    S = S0 * np.exp((mu - 0.5 * sigma**2) * t + sigma * W)

    return t, S

def simulate_multiple_paths(S0, mu, sigma, T, N, num_paths):
    paths = []

    for _ in range(num_paths):
        _, S = simulate_gbm(S0, mu, sigma, T, N)
        paths.append(S)

    return np.array(paths)

def simulate_multiple_paths_vectorized(S0, mu, sigma, T, N, num_paths):
    dt = T / N

    Z = np.random.normal(0, 1, (num_paths, N))


    dW = np.sqrt(dt) * Z

    W = np.cumsum(dW, axis=1)
    W = np.hstack([np.zeros((num_paths, 1)), W])

    t = np.linspace(0, T, N+1)

    S = S0 * np.exp((mu - 0.5 * sigma**2) * t + sigma * W)

    return t, S

W = brownian_motion(T=1, N=500)

plt.plot(W)
plt.title("Brownian Motion")
plt.xlabel("Time Step")
plt.ylabel("Value")
plt.show()

t, S = simulate_gbm(100, 0.1, 0.2, 1, 252)

plt.plot(t, S)
plt.title("Single GBM Path")
plt.xlabel("Time")
plt.ylabel("Price")
plt.show()

t, paths = simulate_multiple_paths_vectorized(
    S0=100, mu=0.1, sigma=0.2, T=1, N=252, num_paths=500
)


for i in range(20):
    plt.plot(t, paths[i], alpha=0.6)

plt.title("Multiple GBM Paths")
plt.xlabel("Time")
plt.ylabel("Price")
plt.show()

final_prices = paths[:, -1]

plt.hist(final_prices, bins=50)
plt.title("Distribution of Final Prices")
plt.xlabel("Price")
plt.ylabel("Frequency")
plt.show()

"""////////////////////////////////////// CORRELATING MULTIPLE ASSETS ///////////////"""

def simulate_multi_asset(S0, mu, sigma, corr_matrix, T, N):
    import numpy as np

    num_assets = len(S0)
    dt = T / N

    L = np.linalg.cholesky(corr_matrix)


    Z = np.random.normal(0, 1, (num_assets, N))

    correlated_Z = L @ Z

    dW = np.sqrt(dt) * correlated_Z
    W = np.cumsum(dW, axis=1)
    W = np.hstack([np.zeros((num_assets, 1)), W])

    t = np.linspace(0, T, N+1)

    S = np.zeros((num_assets, N+1))

    for i in range(num_assets):
        S[i] = S0[i] * np.exp(
            (mu[i] - 0.5 * sigma[i]**2) * t + sigma[i] * W[i]
        )

    return t, S

corr_matrix = np.array([
    [1.0, 0.8, 0.3],
    [0.8, 1.0, 0.5],
    [0.3, 0.5, 1.0]
])

S0 = [100, 120, 80]
mu = [0.1, 0.12, 0.08]
sigma = [0.2, 0.25, 0.15]

t, S = simulate_multi_asset(S0, mu, sigma, corr_matrix, 1, 252)

# Plot
for i in range(len(S)):
    plt.plot(t, S[i], label=f"Asset {i+1}")

plt.legend()
plt.title("Multi-Asset Correlated Prices")
plt.xlabel("Time")
plt.ylabel("Price")
plt.show()

returns = np.diff(np.log(S), axis=1)

corr_estimated = np.corrcoef(returns)

print("Input Correlation Matrix:")
print(corr_matrix)

print("\nEstimated Correlation Matrix:")
print(corr_estimated)

sns.heatmap(corr_estimated, annot=True, cmap="coolwarm")
plt.title("Estimated Correlation Heatmap")
plt.show()

"""////////////////////////////////////////////////// START FEATURE ENGINEERING /////////////////////////////////////////////////"""

import pandas as pd

df = pd.DataFrame(S.T, columns=[f"Asset_{i+1}" for i in range(len(S))])

print(df.head())

returns = df.pct_change().dropna()

print(returns.head())

df["MA_10"] = df["Asset_1"].rolling(window=10).mean() ## moving average

df["Volatility"] = returns["Asset_1"].rolling(window=10).std() ## add volatilty

df["Momentum"] = df["Asset_1"] - df["Asset_1"].shift(5) ## add momentum

df["Lag_1"] = df["Asset_1"].shift(1)  ## lag features
df["Lag_2"] = df["Asset_1"].shift(2)

df = df.dropna()

"""## this is to predict price direction jus tthe  cell following this"""

df["Target"] = (df["Asset_1"].shift(-1) > df["Asset_1"]).astype(int)

df = df.dropna()

print(df.head())

"""################ ML LEARNING MODELS USAGE STARTS ########################"""

features = df.drop(columns=["Target"])
target = df["Target"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    features, target, test_size=0.2, shuffle=False
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression

model_lr = LogisticRegression(max_iter=2000, C=0.1)

model_lr = LogisticRegression(max_iter=1000)

model_lr.fit(X_train_scaled, y_train)

y_pred_lr = model_lr.predict(X_test_scaled)

model_lr = LogisticRegression(max_iter=1000, solver='liblinear')

import pandas as pd

corr_matrix = features.corr().abs()

upper = corr_matrix.where(
    np.triu(np.ones(corr_matrix.shape), k=1).astype(bool)
)

to_drop = [column for column in upper.columns if any(upper[column] > 0.95)]

print("Dropping:", to_drop)

features = features.drop(columns=to_drop)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model_lr.fit(X_train, y_train)
y_pred_lr = model_lr.predict(X_test)

from sklearn.linear_model import LogisticRegression

model_lr = LogisticRegression()
model_lr.fit(X_train, y_train)

y_pred_lr = model_lr.predict(X_test)

"""###########  LOGISTIC REGRESSION ACCURACY =0.5510204081632653"""

from sklearn.metrics import accuracy_score

print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))



"""Decision Tree Accuracy: 0.5306122448979592"""

from sklearn.tree import DecisionTreeClassifier

model_dt = DecisionTreeClassifier(max_depth=5)
model_dt.fit(X_train, y_train)

y_pred_dt = model_dt.predict(X_test)

print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    features, target, test_size=0.2, shuffle=False
)

"""Random Forest Accuracy: 0.46938775510204084"""



from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(n_estimators=100)
model_rf.fit(X_train, y_train)

y_pred_rf = model_rf.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))

from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(n_estimators=100)
model_rf.fit(X_train, y_train)

print("\nModel Comparison:")
print("LR :", accuracy_score(y_test, y_pred_lr))
print("DT :", accuracy_score(y_test, y_pred_dt))
print("RF :", accuracy_score(y_test, y_pred_rf))

import pandas as pd

importance = pd.Series(model_rf.feature_importances_, index=features.columns)

importance.sort_values().plot(kind="barh")
plt.title("Feature Importance")
plt.show()



"""####################################### STARTING WITH ANN PART ######################################"""

features = df.drop(columns=["Target"])
target = df["Target"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    features, target, test_size=0.2, shuffle=False
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

model = Sequential()

model.add(Dense(128, activation='tanh', input_shape=(X_train_scaled.shape[1],)))

model.add(Dense(64, activation='gelu'))

model.add(Dense(32, activation='selu'))

model.add(Dropout(0.3))

model.add(Dense(1, activation='sigmoid'))

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X_train_scaled, y_train,
    epochs=30,
    batch_size=160,
    validation_data=(X_test_scaled, y_test)
)

loss, acc = model.evaluate(X_test_scaled, y_test)

print("ANN Accuracy:", acc)

import matplotlib.pyplot as plt

plt.figure(figsize=(12,5))


plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title("Accuracy over Epochs")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.legend()

plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title("Loss over Epochs")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend()

plt.show()

from sklearn.metrics import confusion_matrix
import seaborn as sns

y_pred_ann = (model.predict(X_test_scaled) > 0.5).astype(int)

cm = confusion_matrix(y_test, y_pred_ann)

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

from sklearn.metrics import roc_curve, auc

y_prob = model.predict(X_test_scaled)

fpr, tpr, _ = roc_curve(y_test, y_prob)
roc_auc = auc(fpr, tpr)

plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.2f}")
plt.plot([0,1], [0,1], linestyle='--')
plt.title("ROC Curve")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.legend()
plt.show()

plt.figure(figsize=(12,5))

plt.plot(y_test.values[:200], label="Actual")
plt.plot(y_pred_ann[:200], label="Predicted")

plt.title("Prediction vs Actual (First 200 points)")
plt.legend()
plt.show()

import seaborn as sns

sns.histplot(y_prob, bins=50, kde=True)
plt.title("Prediction Probability Distribution")
plt.xlabel("Probability")
plt.show()

sns.heatmap(df.corr(), cmap="coolwarm")
plt.title("Feature Correlation Matrix")
plt.show()

returns["Asset_1"].hist(bins=50)
plt.title("Returns Distribution")
plt.xlabel("Returns")
plt.show()

cum_returns = (1 + returns["Asset_1"]).cumprod()

plt.plot(cum_returns)
plt.title("Cumulative Returns")
plt.xlabel("Time")
plt.ylabel("Growth")
plt.show()

from sklearn.metrics import accuracy_score

acc_lr = accuracy_score(y_test, y_pred_lr)
print("Logistic Regression:", acc_lr)

acc_dt = accuracy_score(y_test, y_pred_dt)
print("Decision Tree:", acc_dt)

acc_rf = accuracy_score(y_test, y_pred_rf)
print("Random Forest:", acc_rf)

acc_ann = acc

print("ANN:", acc_ann)

models = ["LR", "DT", "RF", "ANN"]
scores = [acc_lr, acc_dt, acc_rf, acc_ann]

plt.bar(models, scores)
plt.title("Model Accuracy Comparison")
plt.ylabel("Accuracy")
plt.show()

"""////////////////////////////////////////// START LSTM AND TIME SEQUENCING ///////////////////////////////////////"""

def create_sequences(X, y, window_size):
    X_seq = []
    y_seq = []

    for i in range(len(X) - window_size):
        X_seq.append(X[i:i+window_size])
        y_seq.append(y[i+window_size])

    return np.array(X_seq), np.array(y_seq)

window_size = 10

X_values = features.values
y_values = target.values

X_seq, y_seq = create_sequences(X_values, y_values, window_size)

print(X_seq.shape)

split = int(0.8 * len(X_seq))

X_train = X_seq[:split]
X_test = X_seq[split:]

y_train = y_seq[:split]
y_test = y_seq[split:]

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_flat = X_train.reshape(-1, X_train.shape[-1])
X_test_flat = X_test.reshape(-1, X_test.shape[-1])

X_train_scaled = scaler.fit_transform(X_train_flat).reshape(X_train.shape)
X_test_scaled = scaler.transform(X_test_flat).reshape(X_test.shape)

print(X_train_scaled.shape)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

model = Sequential()

model.add(LSTM(128, return_sequences=True, input_shape=(X_train_scaled.shape[1], X_train_scaled.shape[2])))
model.add(Dropout(0.3))

model.add(LSTM(64))
model.add(Dropout(0.3))

model.add(Dense(1, activation='sigmoid'))

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history_lstm = model.fit(
    X_train_scaled, y_train,
    epochs=20,
    batch_size=64,
    validation_data=(X_test_scaled, y_test)
)

import matplotlib.pyplot as plt

plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
plt.plot(history_lstm.history['accuracy'], label='Train')
plt.plot(history_lstm.history['val_accuracy'], label='Validation')
plt.title("LSTM Accuracy")
plt.legend()

plt.subplot(1,2,2)
plt.plot(history_lstm.history['loss'], label='Train')
plt.plot(history_lstm.history['val_loss'], label='Validation')
plt.title("LSTM Loss")
plt.legend()

plt.show()

loss, acc_lstm = model.evaluate(X_test_scaled, y_test)

print("LSTM Accuracy:", acc_lstm)

y_prob_lstm = model.predict(X_test_scaled)
y_pred_lstm = (y_prob_lstm > 0.5).astype(int)

from sklearn.metrics import confusion_matrix
import seaborn as sns

cm = confusion_matrix(y_test, y_pred_lstm)

sns.heatmap(cm, annot=True, fmt='d')
plt.title("LSTM Confusion Matrix")
plt.show()

models = ["LR", "DT", "RF", "ANN", "LSTM"]
scores = [acc_lr, acc_dt, acc_rf, acc_ann, acc_lstm]

plt.bar(models, scores)
plt.title("Model Comparison")
plt.ylabel("Accuracy")
plt.show()

signals = y_pred_lstm.flatten()

returns_test = returns.iloc[-len(signals):]["Asset_1"].values

strategy_returns = signals * returns_test

cum_strategy = (1 + strategy_returns).cumprod()
cum_market = (1 + returns_test).cumprod()

plt.plot(cum_strategy, label="LSTM Strategy")
plt.plot(cum_market, label="Market")
plt.legend()
plt.title("Strategy vs Market (LSTM)")
plt.show()

print("len(y_test):", len(y_test))
print("window:", window)

window = 20   # must be < len(y_test)

window = 50

rolling_acc = []

for i in range(max(1, len(y_test) - window)):
    acc = np.mean(
        y_pred_lstm[i:i+window].flatten() == y_test[i:i+window]
    )
    rolling_acc.append(acc)

print(y_pred_lstm.shape)
print(y_test.shape)

window = 20

y_pred_lstm = y_pred_lstm.flatten()
y_test = y_test.flatten()

rolling_acc = []

for i in range(len(y_test) - window):
    acc = np.mean(
        y_pred_lstm[i:i+window] == y_test[i:i+window]
    )
    rolling_acc.append(acc)

import matplotlib.pyplot as plt
plt.figure(figsize=(10,4))
plt.plot(rolling_acc, color='blue')
plt.axhline(np.mean(rolling_acc), linestyle='--', label='Mean Accuracy')
plt.legend()
plt.grid()
plt.title("Rolling Accuracy Over Time")
plt.show()

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, Dense, Dropout
from tensorflow.keras.layers import Attention


inputs = Input(shape=(X_train_scaled.shape[1], X_train_scaled.shape[2]))


lstm_out = LSTM(64, return_sequences=True)(inputs)
lstm_out = Dropout(0.3)(lstm_out)


attention_out = Attention()([lstm_out, lstm_out])


from tensorflow.keras.layers import Flatten
flat = Flatten()(attention_out)


dense = Dense(32, activation='tanh')(flat)
outputs = Dense(1, activation='sigmoid')(dense)

model_attn = Model(inputs=inputs, outputs=outputs)

model_attn.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history_attn = model_attn.fit(
    X_train_scaled, y_train,
    epochs=20,
    batch_size=64,
    validation_data=(X_test_scaled, y_test)
)

loss, acc_attn = model_attn.evaluate(X_test_scaled, y_test)

print("Attention LSTM Accuracy:", acc_attn)

models = ["LR", "DT", "RF", "ANN", "LSTM", "LSTM+Attention"]
scores = [acc_lr, acc_dt, acc_rf, acc_ann, acc_lstm, acc_attn]

plt.bar(models, scores)
plt.title("Model Comparison")
plt.ylabel("Accuracy")
plt.xticks(rotation=30)
plt.show()

"""/////////////////////////////////////// VISUALIZE ATTENTION //////////////////////////////////"""

import tensorflow as tf
from tensorflow.keras.layers import Layer

class AttentionLayer(Layer):
    def __init__(self):
        super(AttentionLayer, self).__init__()

    def build(self, input_shape):
        self.W = self.add_weight(
            name="att_weight",
            shape=(input_shape[-1], 1),
            initializer="normal"
        )
        self.b = self.add_weight(
            name="att_bias",
            shape=(input_shape[1], 1),
            initializer="zeros"
        )

    def call(self, x):
        e = tf.nn.tanh(tf.matmul(x, self.W) + self.b)
        a = tf.nn.softmax(e, axis=1)
        output = x * a
        return tf.reduce_sum(output, axis=1), a

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, Dense

inputs = Input(shape=(X_train_scaled.shape[1], X_train_scaled.shape[2]))

lstm_out = LSTM(64, return_sequences=True)(inputs)

context_vector, attention_weights = AttentionLayer()(lstm_out)

dense = Dense(32, activation='tanh')(context_vector)
outputs = Dense(1, activation='sigmoid')(dense)

model_attn = Model(inputs=inputs, outputs=[outputs, attention_weights])

model_attn.compile(
    optimizer='adam',
    loss=['binary_crossentropy', None],
    metrics=['accuracy', None]
)

history = model_attn.fit(
    X_train_scaled,
    [y_train, np.zeros((len(y_train), X_train_scaled.shape[1], 1))],
    epochs=20,
    batch_size=64,
    validation_data=(
        X_test_scaled,
        [y_test, np.zeros((len(y_test), X_test_scaled.shape[1], 1))]
    )
)

preds, attn_weights = model_attn.predict(X_test_scaled)

import matplotlib.pyplot as plt
import numpy as np

sample_idx = 0
weights = attn_weights[sample_idx].flatten()

plt.figure(figsize=(10,4))
plt.plot(weights, marker='o')
plt.title("Attention Weights Over Time (Sample 0)")
plt.xlabel("Time Step (Past → Present)")
plt.ylabel("Importance")
plt.grid()
plt.show()

plt.figure(figsize=(10,4))
plt.bar(range(len(weights)), weights)
plt.title("Attention Distribution")
plt.xlabel("Time Step")
plt.ylabel("Weight")
plt.show()

import seaborn as sns

subset = attn_weights[:20].reshape(20, -1)

plt.figure(figsize=(10,6))
sns.heatmap(subset, cmap="viridis")
plt.title("Attention Heatmap (20 Samples)")
plt.xlabel("Time Step")
plt.ylabel("Sample Index")
plt.show()

sample_idx = 0

price_seq = X_test_scaled[sample_idx][:, 0]  # assuming feature 0 = price
weights = attn_weights[sample_idx].flatten()

plt.figure(figsize=(10,4))

plt.plot(price_seq, label="Price (scaled)")
plt.plot(weights * np.max(price_seq), label="Attention (scaled)")

plt.legend()
plt.title("Attention vs Price Movement")
plt.show()

mean_attention = np.mean(attn_weights.reshape(len(attn_weights), -1), axis=0)

plt.figure(figsize=(10,4))
plt.plot(mean_attention)
plt.title("Average Attention Across All Samples")
plt.xlabel("Time Step")
plt.ylabel("Average Importance")
plt.show()

top_k = np.argsort(weights)[-3:]

print("Most important time steps:", top_k)

plt.figure(figsize=(10,5))

for i in range(5):
    plt.plot(attn_weights[i].flatten(), label=f"Sample {i}")

plt.legend()
plt.title("Attention Comparison Across Samples")
plt.show()

weights_norm = weights / np.sum(weights)

plt.figure(figsize=(10,4))
plt.bar(range(len(weights_norm)), weights_norm)
plt.title("Normalized Attention (Sum = 1)")
plt.show()

"""//  **REPORT**


**Attention visualization shows that the model assigns
higher importance to recent time steps, indicating
short-term dependency dominance in financial prediction.**

**WALK FORWARD VALIDATION**
"""

train_size = 500
test_size = 50
step_size = 50

predictions = []
actuals = []

for start in range(0, len(X_seq) - train_size - test_size, step_size):

    end_train = start + train_size
    end_test = end_train + test_size

    X_train_w = X_seq[start:end_train]
    y_train_w = y_seq[start:end_train]

    X_test_w = X_seq[end_train:end_test]
    y_test_w = y_seq[end_train:end_test]


    from sklearn.preprocessing import StandardScaler

    scaler = StandardScaler()

    X_train_flat = X_train_w.reshape(-1, X_train_w.shape[-1])
    X_test_flat = X_test_w.reshape(-1, X_test_w.shape[-1])

    X_train_scaled = scaler.fit_transform(X_train_flat).reshape(X_train_w.shape)
    X_test_scaled = scaler.transform(X_test_flat).reshape(X_test_w.shape)

    from tensorflow.keras.models import Sequential
    from tensorflow.keras.layers import LSTM, Dense

    model = Sequential()
    model.add(LSTM(32, input_shape=(X_train_scaled.shape[1], X_train_scaled.shape[2])))
    model.add(Dense(1, activation='sigmoid'))

    model.compile(optimizer='adam', loss='binary_crossentropy')

    model.fit(X_train_scaled, y_train_w, epochs=5, batch_size=32, verbose=0)

    y_pred = (model.predict(X_test_scaled) > 0.5).astype(int)

    predictions.extend(y_pred.flatten())
    actuals.extend(y_test_w)

from sklearn.metrics import accuracy_score

wf_acc = accuracy_score(actuals, predictions)

print("Walk-forward Accuracy:", wf_acc)

print("Total sequences:", len(X_seq))
print("train_size + test_size:", train_size + test_size)
print("step_size:", step_size)

for start in range(0, len(X_seq) - train_size - test_size, step_size):

    print("Window start:", start)

    end_train = start + train_size
    end_test = end_train + test_size

for start in range(0, len(X_seq) - train_size - test_size, step_size):

    print(f"Start: {start}, Train end: {start+train_size}, Test end: {start+train_size+test_size}")

print(len(X_seq))
print(train_size + test_size)

train_size = 100
test_size = 20
step_size = 20

print("Predictions length:", len(predictions))
print("Actuals length:", len(actuals))

predictions = np.array(predictions).flatten()
actuals = np.array(actuals).flatten()

import matplotlib.pyplot as plt

plt.figure(figsize=(12,5))

if len(predictions) == 0:
    print("No predictions generated — check loop conditions")
else:
    plt.plot(predictions[:200], label="Predicted")
    plt.plot(actuals[:200], label="Actual")

    plt.legend()
    plt.title("Walk-Forward Predictions")
    plt.show()

print("X_seq shape:", X_seq.shape)
print("Length X_seq:", len(X_seq))

print("train_size:", train_size)
print("test_size:", test_size)

print("max usable range:", len(X_seq) - train_size - test_size)

for start in range(0, len(X_seq) - train_size - test_size, step_size):

    print("Running window:", start)

    end_train = start + train_size
    end_test = end_train + test_size

    X_train_w = X_seq[start:end_train]
    y_train_w = y_seq[start:end_train]

    X_test_w = X_seq[end_train:end_test]
    y_test_w = y_seq[end_train:end_test]

    print("X_test shape:", X_test_w.shape)

predictions = []
actuals = []

for start in range(0, len(X_seq) - train_size - test_size, step_size):

    print("Running window:", start)

    end_train = start + train_size
    end_test = end_train + test_size

    X_train_w = X_seq[start:end_train]
    y_train_w = y_seq[start:end_train]

    X_test_w = X_seq[end_train:end_test]
    y_test_w = y_seq[end_train:end_test]


    model.fit(X_train_w, y_train_w, epochs=3, verbose=0)


    y_pred = model.predict(X_test_w)


    predictions.extend(y_pred.flatten())
    actuals.extend(y_test_w)

print("Predictions:", len(predictions))
print("Actuals:", len(actuals))

import matplotlib.pyplot as plt

plt.figure(figsize=(12,5))

plt.plot(predictions[:200], label="Predicted")
plt.plot(actuals[:200], label="Actual")

plt.legend()
plt.title("Walk-Forward Predictions")
plt.show()

"""//// **TRANSFORMER FOR TIME SERIES**"""

import tensorflow as tf
import numpy as np

def positional_encoding(seq_len, d_model):
    positions = np.arange(seq_len)[:, np.newaxis]
    dims = np.arange(d_model)[np.newaxis, :]

    angle_rates = 1 / np.power(10000, (2 * (dims//2)) / np.float32(d_model))
    angle_rads = positions * angle_rates

    angle_rads[:, 0::2] = np.sin(angle_rads[:, 0::2])
    angle_rads[:, 1::2] = np.cos(angle_rads[:, 1::2])

    return tf.cast(angle_rads, dtype=tf.float32)

from tensorflow.keras.layers import LayerNormalization, Dense, Dropout, MultiHeadAttention

class TransformerBlock(tf.keras.layers.Layer):
    def __init__(self, embed_dim, num_heads, ff_dim):
        super().__init__()

        self.att = MultiHeadAttention(num_heads=num_heads, key_dim=embed_dim)
        self.ffn = tf.keras.Sequential([
            Dense(ff_dim, activation="relu"),
            Dense(embed_dim),
        ])

        self.norm1 = LayerNormalization()
        self.norm2 = LayerNormalization()
        self.drop1 = Dropout(0.1)
        self.drop2 = Dropout(0.1)

    def call(self, inputs, training=False):
        attn_output = self.att(inputs, inputs)
        out1 = self.norm1(inputs + attn_output)

        ffn_output = self.ffn(out1)
        ffn_output = self.drop2(ffn_output)

        return self.norm2(out1 + ffn_output)

from tensorflow.keras.layers import Input, Dense, GlobalAveragePooling1D
from tensorflow.keras.models import Model

seq_len = X_train_scaled.shape[1]
features = X_train_scaled.shape[2]

inputs = Input(shape=(seq_len, features))

x = Dense(64)(inputs)

x = x + positional_encoding(seq_len, 64)

x = TransformerBlock(64, 4, 128)(x)
x = TransformerBlock(64, 4, 128)(x)

x = GlobalAveragePooling1D()(x)

x = Dense(32, activation="gelu")(x)
outputs = Dense(1, activation="sigmoid")(x)

model_tf = Model(inputs, outputs)

model_tf.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

history_tf = model_tf.fit(
    X_train_scaled,
    y_train,
    epochs=20,
    batch_size=67,
    validation_data=(X_test_scaled, y_test)
)

loss, acc_tf = model_tf.evaluate(X_test_scaled, y_test)

print("Transformer Accuracy:", acc_tf)

models = ["LR", "DT", "RF", "ANN", "LSTM", "Transformer"]
scores = [acc_lr, acc_dt, acc_rf, acc_ann, acc_lstm, acc_tf]

import matplotlib.pyplot as plt

plt.figure(figsize=(10,4))
plt.bar(models, scores)
plt.title("Model Comparison")
plt.xticks(rotation=30)
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
plt.plot(history_tf.history['accuracy'], label='Train')
plt.plot(history_tf.history['val_accuracy'], label='Validation')
plt.title("Transformer Accuracy")
plt.legend()
plt.grid()

plt.subplot(1,2,2)
plt.plot(history_tf.history['loss'], label='Train')
plt.plot(history_tf.history['val_loss'], label='Validation')
plt.title("Transformer Loss")
plt.legend()
plt.grid()

plt.show()

y_pred_tf = model_tf.predict(X_test_scaled).flatten()

plt.figure(figsize=(12,5))

plt.plot(y_test[:200], label="Actual", linewidth=2)
plt.plot(y_pred_tf[:200], label="Predicted", linestyle="dashed")

plt.title("Transformer: Prediction vs Actual")
plt.legend()
plt.grid()

plt.show()

errors = y_test - y_pred_tf

plt.figure(figsize=(8,4))
plt.hist(errors, bins=30)
plt.title("Prediction Error Distribution")
plt.xlabel("Error")
plt.ylabel("Frequency")
plt.grid()
plt.show()

signals = (y_pred_tf > 0.5).astype(int)

plt.figure(figsize=(12,5))

plt.plot(signals[:200], label="Signal (Buy/Sell)")
plt.plot(y_test[:200], label="Actual Market Movement")

plt.title("Transformer Trading Signals")
plt.legend()
plt.grid()

plt.show()

returns = returns.iloc[-len(signals):]["Asset_1"].values

strategy_returns = signals * returns

cum_strategy = (1 + strategy_returns).cumprod()
cum_market = (1 + returns).cumprod()

plt.figure(figsize=(12,5))

plt.plot(cum_strategy, label="Transformer Strategy")
plt.plot(cum_market, label="Market")

plt.title("Cumulative Returns Comparison")
plt.legend()
plt.grid()

plt.show()

regimes = detect_regime(portfolio_returns)

if regime == "bullish":
    weight = aggressive
elif regime == "bearish":
    weight = defensive
else:
    weight = neutral

"""**PORTFOLIO OPTIMIZATION**"""

returns = np.random.normal(0.001, 0.02, (500, 4))

import numpy as np

mean_returns = np.mean(returns, axis=0)
cov_matrix = np.cov(returns.T)

num_assets = returns.shape[1]
num_portfolios = 10000

results = []

for _ in range(num_portfolios):

    weights = np.random.random(num_assets)
    weights = weights / np.sum(weights)

    port_return = np.dot(weights, mean_returns)

    port_risk = np.sqrt(np.dot(weights.T, np.dot(cov_matrix, weights)))

    sharpe = port_return / port_risk

    results.append((port_return, port_risk, sharpe, weights))

best = max(results, key=lambda x: x[2])

best_return = best[0]
best_risk = best[1]
best_sharpe = best[2]
best_weights = best[3]

print("Best Sharpe:", best_sharpe)
print("Optimal Weights:", best_weights)

import matplotlib.pyplot as plt

returns_list = [r[0] for r in results]
risk_list = [r[1] for r in results]
sharpe_list = [r[2] for r in results]

plt.figure(figsize=(10,6))
plt.scatter(risk_list, returns_list, c=sharpe_list, cmap='viridis')
plt.colorbar(label="Sharpe Ratio")

plt.xlabel("Risk (Volatility)")
plt.ylabel("Return")
plt.title("Efficient Frontier")

plt.show()

portfolio_returns = np.dot(returns, best_weights)

cumulative = (1 + portfolio_returns).cumprod()

plt.figure(figsize=(10,5))
plt.plot(cumulative, label="AI Portfolio Growth")
plt.title("Portfolio Performance Over Time")
plt.legend()
plt.grid()
plt.show()

import matplotlib.pyplot as plt

portfolio_returns = np.dot(returns, best_weights)

cum_strategy = (1 + portfolio_returns).cumprod()
cum_market = (1 + np.mean(returns, axis=1)).cumprod()

plt.figure(figsize=(12,5))
plt.plot(cum_strategy, label="AI Portfolio")
plt.plot(cum_market, label="Market Benchmark")

plt.title("Cumulative Returns: Strategy vs Market")
plt.legend()
plt.grid()
plt.show()

window = 20

rolling_vol = []

for i in range(len(portfolio_returns) - window):
    vol = np.std(portfolio_returns[i:i+window])
    rolling_vol.append(vol)

plt.figure(figsize=(12,5))
plt.plot(rolling_vol)
plt.title("Rolling Portfolio Volatility")
plt.grid()
plt.show()

rolling_ret = []

for i in range(len(portfolio_returns) - window):
    r = np.mean(portfolio_returns[i:i+window])
    rolling_ret.append(r)

plt.figure(figsize=(12,5))
plt.plot(rolling_ret)
plt.title("Rolling Returns")
plt.grid()
plt.show()

rolling_sharpe = []

for i in range(len(portfolio_returns) - window):
    r = portfolio_returns[i:i+window]
    sharpe = np.mean(r) / (np.std(r) + 1e-8)
    rolling_sharpe.append(sharpe)

plt.figure(figsize=(12,5))
plt.plot(rolling_sharpe)
plt.title("Rolling Sharpe Ratio")
plt.grid()
plt.show()

assets = ["A1", "A2", "A3", "A4"]

plt.figure(figsize=(6,6))
plt.pie(best_weights, labels=assets, autopct='%1.1f%%')
plt.title("Optimal Portfolio Allocation")
plt.show()

import seaborn as sns

plt.figure(figsize=(6,5))
sns.heatmap(np.corrcoef(returns.T), annot=True, cmap="coolwarm")
plt.title("Asset Correlation Matrix")
plt.show()

errors = y_test - y_pred_tf

plt.figure(figsize=(8,4))
plt.hist(errors, bins=30)
plt.title("Transformer Prediction Error Distribution")
plt.grid()
plt.show()

plt.figure(figsize=(12,5))
plt.plot(y_test[:150], label="Actual")
plt.plot(y_pred_tf[:150], label="Predicted")
plt.title("Transformer Predictions vs Actual")
plt.legend()
plt.grid()
plt.show()

cum = cum_strategy
peak = np.maximum.accumulate(cum)
drawdown = (cum - peak) / peak

plt.figure(figsize=(12,5))
plt.plot(drawdown, color='blue')
plt.title("Portfolio Drawdown")
plt.grid()
plt.show()

signals = (y_pred_tf > 0.5).astype(int)

plt.figure(figsize=(10,4))
plt.hist(signals, bins=3)
plt.title("Signal Distribution (Buy/Sell)")
plt.xticks([0,1])
plt.grid()
plt.show()

"""**REGIME DETECTION**"""

window = 20

df = pd.DataFrame({
    "returns": portfolio_returns
})

df["rolling_mean"] = df["returns"].rolling(window).mean()
df["rolling_std"] = df["returns"].rolling(window).std()

regime = []

mean_global = np.mean(portfolio_returns)
std_global = np.std(portfolio_returns)

for i in range(len(df)):

    m = df["rolling_mean"].iloc[i]
    s = df["rolling_std"].iloc[i]

    if np.isnan(m) or np.isnan(s):
        regime.append("unknown")

    elif m > mean_global and s < std_global:
        regime.append("bullish")

    elif m < mean_global and s > std_global:
        regime.append("bearish")

    else:
        regime.append("sideways")

df["regime"] = regime

color_map = {
    "bullish": "green",
    "bearish": "red",
    "sideways": "yellow",
    "unknown": "blue"
}

colors = df["regime"].map(color_map)

plt.figure(figsize=(12,5))
plt.scatter(range(len(df)), df["returns"], c=colors, s=10)

plt.title("Market Regimes Over Time")
plt.xlabel("Time")
plt.ylabel("Returns")
plt.show()

plt.figure(figsize=(6,4))
df["regime"].value_counts().plot(kind="bar")
plt.title("Regime Distribution")
plt.show()

plt.figure(figsize=(12,5))

plt.plot(df["rolling_mean"], label="Rolling Mean")
plt.axhline(mean_global, color="black", linestyle="--", label="Global Mean")

plt.legend()
plt.title("Trend Detection")
plt.show()

def detect_regime(returns, window=20):

    df = pd.DataFrame({"r": returns})
    df["mean"] = df["r"].rolling(window).mean()
    df["std"] = df["r"].rolling(window).std()

    regimes = []

    mean_g = np.mean(returns)
    std_g = np.std(returns)

    for i in range(len(df)):
        m = df["mean"].iloc[i]
        s = df["std"].iloc[i]

        if np.isnan(m):
            regimes.append("unknown")

        elif m > mean_g and s < std_g:
            regimes.append("bullish")

        elif m < mean_g and s > std_g:
            regimes.append("bearish")

        else:
            regimes.append("sideways")

    return regimes

aggressive = np.array([0.4, 0.3, 0.2, 0.1])
defensive = np.array([0.1, 0.2, 0.3, 0.4])
neutral = np.array([0.25, 0.25, 0.25, 0.25])

if regime == "bullish":
    weight = aggressive
elif regime == "bearish":
    weight = defensive
else:
    weight = neutral

"""**VALUE AT RISK**

**HISTORICAL METHOD**
"""

import numpy as np

confidence = 0.95

VaR_95= np.percentile(portfolio_returns, (1 - confidence) * 100)

print("Value at Risk (95%):", VaR_95)

""" **You lose more than 2% only 5% of the timE**"""

import matplotlib.pyplot as plt

plt.figure(figsize=(10,4))

plt.hist(portfolio_returns, bins=50, alpha=0.7)
plt.axvline(VaR_95, color='red', label="VaR (95%)")

plt.title("Return Distribution with Value at Risk")
plt.legend()
plt.grid()
plt.show()

CVaR_95 = portfolio_returns[portfolio_returns <= VaR_95].mean()

print("Conditional VaR (95%):", CVaR_95)

"""**PARAMETRIC VALUEATRISK**"""

from scipy.stats import norm

mu = np.mean(returns)
sigma = np.std(returns)

z = norm.ppf(0.05)

VaR_parametric = mu + z * sigma

print("Parametric VaR:", VaR_parametric)

"""**MONTE CARLO VaR**"""

num_simulations = 10000

simulated_returns = np.random.normal(
    np.mean(returns),
    np.std(returns),
    num_simulations
)

num_simulations = 10000

simulated_returns = np.random.normal(
    np.mean(returns),
    np.std(returns),
    num_simulations
)

"""**SIGNAL CONFIDENCE**"""

confidence = np.abs(y_pred) / (np.max(np.abs(y_pred)) + 1e-8)

confidence = 1 / (1 + np.exp(-np.abs(y_pred)))

import matplotlib.pyplot as plt

plt.figure(figsize=(12,4))
plt.plot(confidence[:200], label="Signal Confidence")

plt.title("Confidence Over Time")
plt.legend()
plt.grid()
plt.show()

"""**spikes → strong signals
flat → uncertain market
noisy → unstable model**
"""

threshold = 0.7

filtered_signals = []

for i in range(len(y_pred)):
    if confidence[i] > threshold:
        filtered_signals.append(y_pred[i])
    else:
        filtered_signals.append(0)

plt.figure(figsize=(8,4))

plt.hist(confidence, bins=30)
plt.title("Confidence Distribution")
plt.grid()
plt.show()

plt.figure(figsize=(12,5))

plt.plot(y_pred[:200], label="Prediction")
plt.plot(confidence[:200], label="Confidence")

plt.legend()
plt.title("Prediction vs Confidence")
plt.grid()
plt.show()

final_signal = []

for i in range(len(y_pred)):

    if confidence[i] > 0.7 and y_pred[i] > VaR_mc:
        final_signal.append(1)   # BUY

    elif confidence[i] > 0.7 and y_pred[i] < -VaR_mc:
        final_signal.append(-1)  # SELL

    else:
        final_signal.append(0)   # NO TRADE

"""# **REAL LIFE DATASET INTEGRATION**"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import yfinance as yf

nifty = yf.download("^NSEI", start="2015-01-01", end="2025-01-01")

print(nifty.head())

nifty["returns"] = nifty["Close"].pct_change()

nifty.dropna(inplace=True)

plt.figure(figsize=(12,5))
plt.plot(nifty["Close"])
plt.title("NIFTY 50 Price")
plt.grid()
plt.show()

plt.figure(figsize=(12,5))
plt.plot(nifty["returns"])
plt.title("NIFTY Returns")
plt.grid()
plt.show()

nifty["ma10"] = nifty["Close"].rolling(10).mean()
nifty["ma20"] = nifty["Close"].rolling(20).mean()
nifty["volatility"] = nifty["returns"].rolling(10).std()

nifty.dropna(inplace=True)

features = nifty[["ma10", "ma20", "volatility"]]
target = nifty["returns"]

def create_sequences(data, target, window=20):
    X, y = [], []

    for i in range(len(data)-window):
        X.append(data[i:i+window])
        y.append(target.iloc[i+window])

    return np.array(X), np.array(y)

X, y = create_sequences(features.values, target)

print(X.shape)
print(y.shape)

split = int(len(X)*0.8)

X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

"""# TRANSFORMER FOR NIFTY"""

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers

print(X_train.shape)

inputs = tf.keras.Input(shape=(X_train.shape[1], X_train.shape[2]))

x = layers.Dense(64)(inputs)

attn_output = layers.MultiHeadAttention(
    num_heads=4,
    key_dim=32
)(x, x)

x = layers.Add()([x, attn_output])
x = layers.LayerNormalization()(x)

ff = layers.Dense(128, activation="gelu")(x)
ff = layers.Dense(64, activation="gelu")(ff)

x = layers.Add()([x, ff])
x = layers.LayerNormalization()(x)

x = layers.GlobalAveragePooling1D()(x)

outputs = layers.Dense(1)(x)

model_tf = tf.keras.Model(inputs, outputs)

model_tf.compile(
    optimizer="adam",
    loss="mse"
)

model_tf.summary()

history = model_tf.fit(
    X_train,
    y_train,
    validation_data=(X_test, y_test),
    epochs=20,
    batch_size=32
)

import matplotlib.pyplot as plt

plt.plot(history.history["loss"], label="Train Loss")
plt.plot(history.history["val_loss"], label="Val Loss")

plt.title("Transformer Training Loss (NIFTY)")
plt.legend()
plt.grid()
plt.show()

y_pred = model_tf.predict(X_test).flatten()

plt.figure(figsize=(12,5))

plt.plot(y_test[:200], label="Actual")
plt.plot(y_pred[:200], label="Predicted")

plt.title("NIFTY Return Prediction - Transformer")
plt.legend()
plt.grid()
plt.show()

"""## SIGNAL GENERARTION FOR NIFTY"""

import numpy as np

threshold = np.std(y_pred) * 0.5
print("Threshold:", threshold)

signals = []

for pred in y_pred:
    if pred > threshold:
        signals.append(1)
    elif pred < -threshold:
        signals.append(-1)
    else:
        signals.append(0)

import matplotlib.pyplot as plt

plt.figure(figsize=(12,4))
plt.plot(signals[:200], label="Trading Signals")

plt.title("NIFTY Transformer Trading Signals")
plt.legend()
plt.grid()
plt.show()

confidence = np.abs(y_pred) / (np.max(np.abs(y_pred)) + 1e-8)

final_signals = []

for i in range(len(y_pred)):

    if confidence[i] < 0.6:
        final_signals.append(0)

    else:
        if y_pred[i] > threshold:
            final_signals.append(1)
        elif y_pred[i] < -threshold:
            final_signals.append(-1)
        else:
            final_signals.append(0)

plt.figure(figsize=(12,4))
plt.plot(final_signals[:200], label="Filtered Signals")

plt.title("Confidence + Threshold Filtered Signals")
plt.legend()
plt.grid()
plt.show()

strategy_returns = []

for i in range(len(final_signals)):

    strategy_returns.append(final_signals[i] * y_test[i])

cumulative = np.cumsum(strategy_returns)

plt.figure(figsize=(12,5))
plt.plot(cumulative)

plt.title("Strategy Performance (Transformer on NIFTY)")
plt.grid()
plt.show()

"""**TRIPLE BARRIER METHOD**


**UPPER BARRIER =+1

LOWER BARRIER=-1

AND VERTICAL BARRIER=0**

# BACK TESTING ENGINE
"""

final_signals
nifty["returns"]

returns = nifty["returns"].iloc[-len(final_signals):].values
signals = np.array(final_signals)

strategy_returns = signals * returns

cumulative_returns = np.cumsum(strategy_returns)

import matplotlib.pyplot as plt

plt.figure(figsize=(12,5))
plt.plot(cumulative_returns)

plt.title("Cumulative Strategy Returns (Backtest)")
plt.grid()
plt.show()

buy_hold = np.cumsum(returns)

plt.figure(figsize=(12,5))

plt.plot(cumulative_returns, label="Strategy")
plt.plot(buy_hold, label="Buy & Hold")

plt.title("Strategy vs Market Benchmark")
plt.legend()
plt.grid()
plt.show()

print("Strategy stats:")
print(np.min(cumulative_returns), np.max(cumulative_returns))

print("\nBuy & Hold stats:")
print(np.min(buy_hold), np.max(buy_hold))

print(len(cumulative_returns))
print(len(buy_hold))

returns = np.array(returns)

strategy_returns = np.array(strategy_returns)

cumulative_returns = np.cumsum(strategy_returns)
buy_hold = np.cumsum(returns[:len(strategy_returns)])

plt.figure(figsize=(12,5))

plt.plot(cumulative_returns, label="Strategy", linestyle="--", linewidth=2)
plt.plot(buy_hold, label="Buy & Hold", linestyle="-", linewidth=2)

plt.title("Strategy vs Market Benchmark")
plt.legend()
plt.grid()
plt.show()

strategy_norm = cumulative_returns / (np.max(np.abs(cumulative_returns)) + 1e-8)
buy_hold_norm = buy_hold / (np.max(np.abs(buy_hold)) + 1e-8)

plt.figure(figsize=(12,5))

plt.plot(strategy_norm, label="Strategy")
plt.plot(buy_hold_norm, label="Buy & Hold")

plt.legend()
plt.grid()
plt.show()

print(np.unique(signals, return_counts=True))

"""## WORST LOSS PERIOD"""

running_max = np.maximum.accumulate(cumulative_returns)
drawdown = cumulative_returns - running_max

plt.figure(figsize=(12,4))
plt.plot(drawdown, color="red")

plt.title("Drawdown Curve")
plt.grid()
plt.show()

total_return = cumulative_returns[-1]
volatility = np.std(strategy_returns)
sharpe = np.mean(strategy_returns) / (volatility + 1e-8)

print("Total Return:", total_return)
print("Volatility:", volatility)
print("Sharpe Ratio:", sharpe)

cost = 0.0005

strategy_returns = (signals * returns) - cost * np.abs(np.diff(signals, prepend=0))

position = 0.5

strategy_returns = position * signals * returns

"""## PORTFOLIO BACKTESTING"""

import yfinance as yf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

tickers = ["RELIANCE.NS", "TCS.NS", "INFY.NS", "HDFCBANK.NS"]

data = yf.download(tickers, start="2018-01-01")["Close"]

returns = data.pct_change().dropna()

weights = np.array([0.25, 0.25, 0.25, 0.25])

portfolio_returns = returns.dot(weights)

cumulative = (1 + portfolio_returns).cumprod()

plt.figure(figsize=(12,5))

plt.plot(cumulative, label="Portfolio Growth")

plt.title("Multi-Asset Portfolio Backtest (NIFTY Stocks)")
plt.legend()
plt.grid()
plt.show()

nifty = yf.download("^NSEI", start="2018-01-01")["Close"]
nifty_ret = nifty.pct_change().dropna()

nifty_cum = (1 + nifty_ret).cumprod()

import numpy as np

cumulative = np.array(cumulative).reshape(-1)
nifty_cum = np.array(nifty_cum).reshape(-1)

import pandas as pd

cumulative = pd.Series(cumulative)
nifty_cum = pd.Series(nifty_cum)

aligned = pd.concat([cumulative, nifty_cum], axis=1).dropna()
aligned.columns = ["Portfolio", "NIFTY"]

import matplotlib.pyplot as plt

plt.figure(figsize=(12,5))

plt.plot(aligned["Portfolio"], label="Portfolio")
plt.plot(aligned["NIFTY"], label="NIFTY Benchmark")

plt.title("Portfolio vs NIFTY Benchmark")
plt.legend()
plt.grid()
plt.show()

vol = np.std(portfolio_returns)
print("Portfolio Volatility:", vol)

sharpe = np.mean(portfolio_returns) / (np.std(portfolio_returns) + 1e-8)
print("Sharpe Ratio:", sharpe)

running_max = np.maximum.accumulate(cumulative)
drawdown = cumulative - running_max

plt.figure(figsize=(12,4))
plt.plot(drawdown, color="red")
plt.title("Portfolio Drawdown")
plt.grid()
plt.show()

vol = returns.std()

weights = 1 / vol
weights = weights / weights.sum()

"""**VOLATILITY BASED WEIGHTS **


**Inverse Volatility Portfolio**
"""

vol = returns.std()

inv_vol = 1 / vol

weights = inv_vol / inv_vol.sum()

print(weights)

portfolio_returns = returns.dot(weights)

cumulative = (1 + portfolio_returns).cumprod()

import matplotlib.pyplot as plt

plt.figure(figsize=(12,5))
plt.plot(cumulative)

plt.title("Volatility-Based Portfolio")
plt.grid()
plt.show()

"""## ROLLING VOLATILITY
**RIGHT NOW WEIGHTS ARE FIXED BUT REAL SYSTEM USE DYNAMIC WEIGHTS**
"""

rolling_vol = returns.rolling(window=20).std()

weights_dynamic = (1 / rolling_vol)
weights_dynamic = weights_dynamic.div(weights_dynamic.sum(axis=1), axis=0)

portfolio_returns_dyn = (weights_dynamic.shift(1) * returns).sum(axis=1)

cumulative_dyn = (1 + portfolio_returns_dyn).cumprod()

plt.figure(figsize=(12,5))
plt.plot(cumulative_dyn)

plt.title("Dynamic Volatility-Based Portfolio")
plt.grid()
plt.show()

print("Shape of aligned:", aligned.shape)
print(aligned.head())

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

cumulative_dyn = pd.Series(np.array(cumulative_dyn).reshape(-1))
nifty_cum = pd.Series(np.array(nifty_cum).reshape(-1))

min_len = min(len(cumulative_dyn), len(nifty_cum))

aligned = pd.DataFrame({
    "Portfolio": cumulative_dyn[-min_len:].values,
    "NIFTY": nifty_cum[-min_len:].values
})

plt.figure(figsize=(12,5))

plt.plot(aligned["Portfolio"], label="Volatility Portfolio")
plt.plot(aligned["NIFTY"], label="NIFTY")

plt.legend()
plt.grid()
plt.show()

portfolio = aligned["Portfolio"]
benchmark = aligned["NIFTY"]

portfolio_ret = portfolio.pct_change().dropna()
benchmark_ret = benchmark.pct_change().dropna()

sharpe = portfolio_ret.mean() / (portfolio_ret.std() + 1e-8)

print("Portfolio Sharpe Ratio:", sharpe)

sharpe_benchmark = benchmark_ret.mean() / (benchmark_ret.std() + 1e-8)

print("NIFTY Sharpe Ratio:", sharpe_benchmark)

alpha = portfolio_ret.mean() - benchmark_ret.mean()

print("Alpha:", alpha)

cum = (1 + portfolio_ret).cumprod()

running_max = cum.cummax()
drawdown = cum - running_max

max_dd = drawdown.min()

print("Max Drawdown:", max_dd)

import matplotlib.pyplot as plt

plt.figure(figsize=(12,4))
plt.plot(drawdown, color="red")

plt.title("Drawdown Curve")
plt.grid()
plt.show()

plt.figure(figsize=(12,5))

plt.plot(portfolio, label="Portfolio")
plt.plot(benchmark, label="NIFTY")

plt.title("Final Portfolio vs NIFTY")
plt.legend()
plt.grid()
plt.show()

"""# REAL IMPLEMENTATION COULLD SEE MODEL IS BUYING OR SELLING"""

plt.figure(figsize=(14,6))

plt.plot(aligned["NIFTY"], label="NIFTY Price", alpha=0.6)

buy_idx = np.where(np.array(final_signals) == 1)[0]
sell_idx = np.where(np.array(final_signals) == -1)[0]

plt.scatter(buy_idx, aligned["NIFTY"].iloc[buy_idx], marker="^", label="BUY")
plt.scatter(sell_idx, aligned["NIFTY"].iloc[sell_idx], marker="v", label="SELL")

plt.title("Trading Signals on NIFTY")
plt.legend()
plt.grid()
plt.show()

signals = np.array(final_signals)

nifty_prices = aligned["NIFTY"].values

min_len = min(len(signals), len(nifty_prices))

signals = signals[-min_len:]
nifty_prices = nifty_prices[-min_len:]

buy_idx = np.where(signals == 1)[0]
sell_idx = np.where(signals == -1)[0]

threshold = np.std(y_pred) * 0.2

upper = np.percentile(y_pred, 70)
lower = np.percentile(y_pred, 30)

signals = []

for p in y_pred:
    if p > upper:
        signals.append(1)
    elif p < lower:
        signals.append(-1)
    else:
        signals.append(0)

y_pred = (y_pred - np.mean(y_pred)) / (np.std(y_pred) + 1e-8)

print(np.unique(signals, return_counts=True))

import matplotlib.pyplot as plt

plt.hist(y_pred, bins=50)
plt.title("Prediction Distribution")
plt.grid()
plt.show()

upper = np.percentile(y_pred, 65)
lower = np.percentile(y_pred, 35)

signals = np.where(y_pred > upper, 1,
           np.where(y_pred < lower, -1, 0))

print("Signals:", np.unique(signals, return_counts=True))

print("Min:", np.min(y_pred))
print("Max:", np.max(y_pred))
print("Mean:", np.mean(y_pred))

plt.hist(y_pred, bins=50)
plt.title("Prediction Distribution")
plt.grid()
plt.show()

threshold = np.std(y_pred) * 0.5

signals = np.where(
    y_pred > threshold, 1,
    np.where(y_pred < -threshold, -1, 0)
)

upper = np.percentile(y_pred, 65)
lower = np.percentile(y_pred, 35)

signals = np.where(
    y_pred > upper, 1,
    np.where(y_pred < lower, -1, 0)
)

print(np.unique(signals, return_counts=True))

upper = np.percentile(y_pred, 80)
lower = np.percentile(y_pred, 20)

plt.figure(figsize=(12,4))
plt.plot(signals)
plt.title("Signals Timeline")
plt.grid()
plt.show()

signals = np.array(signals)
prices = np.array(aligned["NIFTY"])

min_len = min(len(signals), len(prices))

signals = signals[-min_len:]
prices = prices[-min_len:]

buy_idx = np.where(signals == 1)[0]
sell_idx = np.where(signals == -1)[0]

plt.figure(figsize=(14,6))

plt.plot(prices, label="NIFTY")

plt.scatter(buy_idx, prices[buy_idx], color="green", marker="^", s=80, label="BUY")
plt.scatter(sell_idx, prices[sell_idx], color="red", marker="v", s=80, label="SELL")

plt.legend()
plt.grid()
plt.show()

plt.scatter(buy_idx, nifty_prices[buy_idx], marker="^", color="green", s=100, label="BUY")
plt.scatter(sell_idx, nifty_prices[sell_idx], marker="v", color="red", s=100, label="SELL")

"""# BANK BALANCE"""

equity = (1 + portfolio_ret).cumprod()

plt.figure(figsize=(12,5))
plt.plot(equity)
plt.title("Portfolio Equity Curve (Money Growth)")
plt.grid()
plt.show()

plt.figure(figsize=(6,6))

plt.scatter(portfolio_ret.std(), portfolio_ret.mean(), label="Portfolio")
plt.scatter(benchmark_ret.std(), benchmark_ret.mean(), label="NIFTY")

plt.xlabel("Risk (Volatility)")
plt.ylabel("Return")
plt.title("Risk vs Return")
plt.legend()
plt.grid()
plt.show()

"""# RED=STRONG CONVICTION

 BLUE=WEAK
"""

import seaborn as sns

sns.heatmap(confidence.reshape(-1,1), cmap="coolwarm")
plt.title("Signal Confidence Over Time")
plt.show()

rolling_acc = []

window = 50

for i in range(window, len(y_pred)):
    pred = np.sign(y_pred[i-window:i])
    actual = np.sign(y_test[i-window:i])

    acc = np.mean(pred == actual)
    rolling_acc.append(acc)

plt.figure(figsize=(12,4))
plt.plot(rolling_acc)
plt.title("Rolling Prediction Accuracy")
plt.grid()
plt.show()

"""# **❌ MODEL FAILURE**"""

failure_threshold = 0.45

"""# RED SHADED AREA=MODEL FAILING AND LINE BELOW THRESHOLD=WEAK PERFORMANCE"""

plt.figure(figsize=(12,4))

plt.plot(rolling_acc, label="Rolling Accuracy")

for i, val in enumerate(rolling_acc):
    if val < failure_threshold:
        plt.axvspan(i, i+1, color='red', alpha=0.2)

plt.axhline(failure_threshold, color='black', linestyle='--', label="Failure Threshold")

plt.title("Rolling Accuracy with Failure Zones")
plt.legend()
plt.grid()
plt.show()

fail_periods = []

for i, val in enumerate(rolling_acc):
    if val < failure_threshold:
        fail_periods.append(i)

print("Failure indices:", fail_periods[:20])
print("Total failure points:", len(fail_periods))

plt.figure(figsize=(12,5))

plt.plot(aligned["NIFTY"].values[window:], label="NIFTY")

for i in fail_periods:
    plt.axvspan(i, i+1, color='red', alpha=0.1)

plt.title("Model Failure vs Market Movement")
plt.legend()
plt.grid()
plt.show()

pred_sign = np.sign(y_pred)
actual_sign = np.sign(y_test)

wrong = pred_sign != actual_sign

plt.figure(figsize=(12,4))
plt.plot(wrong.astype(int))
plt.title("Wrong Predictions Timeline (1 = wrong)")
plt.grid()
plt.show()

error = np.abs(y_pred - y_test)

plt.figure(figsize=(12,4))
plt.plot(error)
plt.title("Prediction Error Magnitude")
plt.grid()
plt.show()

"""# STOP TRADING DURING FAILURE"""

if rolling_acc[i] < 0.45:
    signal = 0

weight = rolling_acc[i]

print("========== FINAL SYSTEM SUMMARY ==========")
print("Total Return:", equity.iloc[-1])
print("Sharpe Ratio:", sharpe)
print("Alpha:", alpha)
print("Max Drawdown:", max_dd)

"""# ✨ANIMATED TRADING:"""

prices = aligned["NIFTY"].values
signals = np.array(signals)

import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
import numpy as np

fig, ax = plt.subplots(figsize=(12,6))

x_data, y_data = [], []

line, = ax.plot([], [], lw=2)
buy_scatter = ax.scatter([], [], marker="^", color="green", s=80, label="BUY")
sell_scatter = ax.scatter([], [], marker="v", color="red", s=80, label="SELL")

ax.set_title("Animated Trading Chart")
ax.legend()
ax.grid()

buy_x, buy_y = [], []
sell_x, sell_y = [], []

def update(frame):
    x_data.append(frame)
    y_data.append(prices[frame])

    line.set_data(x_data, y_data)

    if signals[frame] == 1:
        buy_x.append(frame)
        buy_y.append(prices[frame])
    elif signals[frame] == -1:
        sell_x.append(frame)
        sell_y.append(prices[frame])

    buy_scatter.set_offsets(np.c_[buy_x, buy_y])
    sell_scatter.set_offsets(np.c_[sell_x, sell_y])

    ax.set_xlim(0, frame + 10)
    ax.set_ylim(min(prices[:frame+1])*0.98, max(prices[:frame+1])*1.02)

    return line, buy_scatter, sell_scatter

ani = FuncAnimation(
    fig,
    update,
    frames=len(prices),
    interval=50,
    repeat=False
)

plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML


prices = np.array(aligned["NIFTY"]).reshape(-1)
signals = np.array(signals).reshape(-1)

min_len = min(len(prices), len(signals))
prices = prices[-min_len:]
signals = signals[-min_len:]


fig, ax = plt.subplots(figsize=(12,6))

x_data, y_data = [], []

line, = ax.plot([], [], lw=2)

buy_scatter = ax.scatter([], [], marker="^", color="green", s=100, label="BUY")
sell_scatter = ax.scatter([], [], marker="v", color="red", s=100, label="SELL")

ax.set_title("Animated Trading Chart")
ax.legend()
ax.grid()



buy_x, buy_y = [], []
sell_x, sell_y = [], []


def update(frame):

    x_data.append(frame)
    y_data.append(prices[frame])

    line.set_data(x_data, y_data)

    if signals[frame] == 1:
        buy_x.append(frame)
        buy_y.append(prices[frame])

    elif signals[frame] == -1:
        sell_x.append(frame)
        sell_y.append(prices[frame])

    if len(buy_x) > 0:
        buy_scatter.set_offsets(np.c_[buy_x, buy_y])

    if len(sell_x) > 0:
        sell_scatter.set_offsets(np.c_[sell_x, sell_y])

    window = 100
    ax.set_xlim(max(0, frame-window), frame+5)

    ax.set_ylim(
        np.min(prices[max(0, frame-window):frame+1]) * 0.98,
        np.max(prices[max(0, frame-window):frame+1]) * 1.02
    )

    return line, buy_scatter, sell_scatter



ani = FuncAnimation(
    fig,
    update,
    frames=len(prices),
    interval=50,
    repeat=False
)


HTML(ani.to_jshtml())

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

prices = np.array(aligned["NIFTY"]).reshape(-1)
signals = np.array(signals).reshape(-1)

min_len = min(len(prices), len(signals))
prices = prices[-min_len:]
signals = signals[-min_len:]

print("Data length:", len(prices))

fig, ax = plt.subplots(figsize=(12,6))

x_data, y_data = [], []

line, = ax.plot([], [], lw=2)

buy_scatter = ax.scatter([], [], marker="^", color="green", s=80, label="BUY")
sell_scatter = ax.scatter([], [], marker="v", color="red", s=80, label="SELL")

ax.set_title("Animated Trading Chart")
ax.legend()
ax.grid()


buy_x, buy_y = [], []
sell_x, sell_y = [], []



def update(frame):

    x_data.append(frame)
    y_data.append(prices[frame])
    line.set_data(x_data, y_data)

    if signals[frame] == 1:
        buy_x.append(frame)
        buy_y.append(prices[frame])

    elif signals[frame] == -1:
        sell_x.append(frame)
        sell_y.append(prices[frame])

    if len(buy_x) > 0:
        buy_scatter.set_offsets(np.c_[buy_x, buy_y])

    if len(sell_x) > 0:
        sell_scatter.set_offsets(np.c_[sell_x, sell_y])

    window = 100
    ax.set_xlim(max(0, frame-window), frame+5)

    ymin = np.min(prices[max(0, frame-window):frame+1])
    ymax = np.max(prices[max(0, frame-window):frame+1])

    ax.set_ylim(ymin * 0.98, ymax * 1.02)

    return line, buy_scatter, sell_scatter


ani = FuncAnimation(
    fig,
    update,
    frames=len(prices),
    interval=50,
    repeat=False
)


HTML(ani.to_jshtml())

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML


prices = np.array(aligned["NIFTY"]).reshape(-1)
signals = np.array(signals).reshape(-1)

min_len = min(len(prices), len(signals))
prices = prices[-min_len:]
signals = signals[-min_len:]

returns = np.diff(prices) / prices[:-1]
returns = np.insert(returns, 0, 0)


fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12,8))

x_data, y_data = [], []
price_line, = ax1.plot([], [], lw=2)

buy_scatter = ax1.scatter([], [], marker="^", color="green", s=80, label="BUY")
sell_scatter = ax1.scatter([], [], marker="v", color="red", s=80, label="SELL")

ax1.set_title("Trading Signals")
ax1.legend()
ax1.grid()

equity_data = []
pnl_line, = ax2.plot([], [], lw=2)

ax2.set_title("PnL (Equity Curve)")
ax2.grid()


buy_x, buy_y = [], []
sell_x, sell_y = [], []

equity = 1
position = 0


def update(frame):
    global equity, position

    x_data.append(frame)
    y_data.append(prices[frame])
    price_line.set_data(x_data, y_data)

    if signals[frame] == 1:
        position = 1
        buy_x.append(frame)
        buy_y.append(prices[frame])

    elif signals[frame] == -1:
        position = -1
        sell_x.append(frame)
        sell_y.append(prices[frame])
    equity = equity * (1 + position * returns[frame])
    equity_data.append(equity)

    if len(buy_x) > 0:
        buy_scatter.set_offsets(np.c_[buy_x, buy_y])
    if len(sell_x) > 0:
        sell_scatter.set_offsets(np.c_[sell_x, sell_y])

    pnl_line.set_data(range(len(equity_data)), equity_data)

    window = 100

    ax1.set_xlim(max(0, frame-window), frame+5)
    ax1.set_ylim(
        np.min(prices[max(0, frame-window):frame+1]) * 0.98,
        np.max(prices[max(0, frame-window):frame+1]) * 1.02
    )

    ax2.set_xlim(0, len(equity_data))
    ax2.set_ylim(min(equity_data)*0.98, max(equity_data)*1.02)

    return price_line, buy_scatter, sell_scatter, pnl_line


ani = FuncAnimation(
    fig,
    update,
    frames=len(prices),
    interval=50,
    repeat=False
)



HTML(ani.to_jshtml())

"""## ⌛WIN LOSS CURVE"""

trade_results = []

position = 0
entry_price = None

for i in range(len(prices)):
    signal = signals[i]

    # ENTRY / SWITCH
    if signal == 1 and position != 1:
        if position != 0 and entry_price is not None:
            pnl = (prices[i] - entry_price) * position
            trade_results.append(1 if pnl > 0 else -1)

        position = 1
        entry_price = prices[i]

    elif signal == -1 and position != -1:
        if position != 0 and entry_price is not None:
            pnl = (prices[i] - entry_price) * position
            trade_results.append(1 if pnl > 0 else -1)

        position = -1
        entry_price = prices[i]

import numpy as np

trade_results = np.array(trade_results)

win_loss_curve = np.cumsum(trade_results)

"""## UPWARD- STRATEGY WORKING ,FLAT=RANDOM,DOWNWARD=LOSING SYSTEM"""

plt.figure(figsize=(12,5))

plt.plot(win_loss_curve, color="pink")


plt.fill_between(range(len(win_loss_curve)), win_loss_curve,
                 where=(win_loss_curve >= 0), alpha=0.2)

plt.fill_between(range(len(win_loss_curve)), win_loss_curve,
                 where=(win_loss_curve < 0), alpha=0.2)

plt.axhline(0, linestyle='--')

plt.title("Win/Loss Performance Curve")
plt.grid()
plt.show()



win_rate = np.cumsum(trade_results == 1) / np.arange(1, len(trade_results)+1)

plt.figure(figsize=(12,4))
plt.plot(win_rate)

plt.title("Win Rate Over Time")
plt.ylabel("Win %")
plt.grid()
plt.show()

"""# CANDLESTICK ANIMATION"""

import numpy as np
import pandas as pd

close = np.array(aligned["NIFTY"]).reshape(-1)

open_ = np.roll(close, 1)
open_[0] = close[0]

high = np.maximum(open_, close) + np.random.rand(len(close)) * 0.002 * close
low = np.minimum(open_, close) - np.random.rand(len(close)) * 0.002 * close

df = pd.DataFrame({
    "Open": open_,
    "High": high,
    "Low": low,
    "Close": close
})

!pip install mplfinance

import mplfinance as mpf
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

df.index = pd.date_range(start="2020-01-01", periods=len(df), freq="D")

fig, ax = plt.subplots(figsize=(10,6))

window = 40

def update(i):
    ax.clear()

    start = max(0, i - window)
    data = df.iloc[start:i+1]

    mpf.plot(
        data,
        type='candle',
        ax=ax,
        style='charles',
        show_nontrading=False
    )

    ax.set_title("Candlestick Animation (Fast)")

frames = range(0, len(df), 5)

ani = FuncAnimation(
    fig,
    update,
    frames=frames,
    interval=80,
    repeat=False
)

HTML(ani.to_jshtml())

def update(i):
    ax.clear()

    data = df.iloc[:i+1]

    mpf.plot(
        data,
        type='candle',
        ax=ax,
        style='charles',
        show_nontrading=True
    )

    # signals
    if i < len(signals):
        if signals[i] == 1:
            ax.scatter(i, df["Close"].iloc[i], marker="^", color="purple", s=100)
        elif signals[i] == -1:
            ax.scatter(i, df["Close"].iloc[i], marker="v", color="orange", s=100)

"""# PLOTLY VERSION"""

!pip install plotly

df.index = pd.date_range(start="2020-01-01", periods=len(df), freq="D")

signals = np.array(signals)

# align lengths
min_len = min(len(df), len(signals))
df = df.iloc[-min_len:]
signals = signals[-min_len:]

import plotly.graph_objects as go

fig = go.Figure()


fig.add_trace(go.Candlestick(
    x=df.index,
    open=df['Open'],
    high=df['High'],
    low=df['Low'],
    close=df['Close'],
    name="Price"
))

buy_idx = np.where(signals == 1)[0]
sell_idx = np.where(signals == -1)[0]

fig.add_trace(go.Scatter(
    x=df.index[buy_idx],
    y=df['Close'].iloc[buy_idx],
    mode='markers',
    marker=dict(symbol='triangle-up', size=10),
    name='BUY'
))

fig.add_trace(go.Scatter(
    x=df.index[sell_idx],
    y=df['Close'].iloc[sell_idx],
    mode='markers',
    marker=dict(symbol='triangle-down', size=10),
    name='SELL'
))

fig.update_layout(
    title="Interactive Trading Chart",
    xaxis_title="Time",
    yaxis_title="Price",
    xaxis_rangeslider_visible=False,
    template="plotly_dark",
    height=600
)

fig.show()

df["MA20"] = df["Close"].rolling(20).mean()
df["MA50"] = df["Close"].rolling(50).mean()

fig.add_trace(go.Scatter(
    x=df.index,
    y=df["MA20"],
    name="MA20"
))

fig.add_trace(go.Scatter(
    x=df.index,
    y=df["MA50"],
    name="MA50"
))

from plotly.subplots import make_subplots

fig = make_subplots(rows=2, cols=1, shared_xaxes=True)

fig.update_layout(
    xaxis=dict(
        rangeselector=dict(
            buttons=list([
                dict(count=7, label="1w", step="day", stepmode="backward"),
                dict(count=30, label="1m", step="day", stepmode="backward"),
                dict(step="all")
            ])
        )
    )
)

np.save("X_seq.npy", X_seq)
np.save("y_seq.npy", y_seq)

"""# RSI(RELATIVE STRENTGH INDEX),MACD(MOVING AVERAGE CONVERGENCE DIVERGENECE):::::::

**RSI TELLS WHETHER A STOCK IS OVERBOUGHT OR OVERSOLD,BASICALLY IT MEASURES THE SPEED AND MACD IS THE TREND AND MOMENTUM INDICATOR**
"""

import tensorflow as tf
from tensorflow.keras import layers, Input

def build_lstm(hidden=64, dropout=0.2, input_shape=None):
    model = tf.keras.Sequential([
        Input(shape=input_shape),
        layers.LSTM(hidden),
        layers.Dropout(dropout),
        layers.Dense(1)
    ])
    return model

model = build_lstm(64, 0.2, X_train.shape[1:])

y_pred = model.predict(X_val).flatten()

import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots


df.index = pd.date_range(start="2020-01-01", periods=len(df), freq="D")

signals = np.array(signals)

min_len = min(len(df), len(signals))
df = df.iloc[-min_len:]
signals = signals[-min_len:]

prices = df["Close"].values


returns = np.diff(prices) / prices[:-1]
returns = np.insert(returns, 0, 0)

equity = 1
equity_curve = []
position = 0

for i in range(len(prices)):
    if signals[i] == 1:
        position = 1
    elif signals[i] == -1:
        position = -1

    equity = equity * (1 + position * returns[i])
    equity_curve.append(equity)

equity_curve = np.array(equity_curve)


delta = df["Close"].diff()

gain = delta.clip(lower=0)
loss = -delta.clip(upper=0)

avg_gain = gain.rolling(14).mean()
avg_loss = loss.rolling(14).mean()

rs = avg_gain / (avg_loss + 1e-8)
rsi = 100 - (100 / (1 + rs))


ema12 = df["Close"].ewm(span=12).mean()
ema26 = df["Close"].ewm(span=26).mean()

macd = ema12 - ema26
signal_line = macd.ewm(span=9).mean()


fig = make_subplots(
    rows=4, cols=1,
    shared_xaxes=True,
    vertical_spacing=0.02,
    row_heights=[0.4, 0.2, 0.2, 0.2]
)



fig.add_trace(go.Candlestick(
    x=df.index,
    open=df["Open"],
    high=df["High"],
    low=df["Low"],
    close=df["Close"],
    name="Price"
), row=1, col=1)

buy_idx = np.where(signals == 1)[0]
sell_idx = np.where(signals == -1)[0]

fig.add_trace(go.Scatter(
    x=df.index[buy_idx],
    y=df["Close"].iloc[buy_idx],
    mode="markers",
    marker=dict(symbol="triangle-up", size=10),
    name="BUY"
), row=1, col=1)

fig.add_trace(go.Scatter(
    x=df.index[sell_idx],
    y=df["Close"].iloc[sell_idx],
    mode="markers",
    marker=dict(symbol="triangle-down", size=10),
    name="SELL"
), row=1, col=1)


fig.add_trace(go.Scatter(
    x=df.index,
    y=rsi,
    name="RSI"
), row=2, col=1)

fig.add_hline(y=70, line_dash="dash", row=2, col=1)
fig.add_hline(y=30, line_dash="dash", row=2, col=1)

fig.add_trace(go.Scatter(
    x=df.index,
    y=macd,
    name="MACD"
), row=3, col=1)

fig.add_trace(go.Scatter(
    x=df.index,
    y=signal_line,
    name="Signal Line"
), row=3, col=1)


fig.add_trace(go.Scatter(
    x=df.index,
    y=equity_curve,
    name="Equity Curve"
), row=4, col=1)



fig.update_layout(
    title="Advanced Trading Dashboard",
    template="plotly_dark",
    height=900,
    xaxis_rangeslider_visible=False
)

fig.show()

"""# ❤:MAI KAHA LADLE PnL TOH PROFIT DIKHA DIYA RISK KON DIKHAYEGA"""

peak = np.maximum.accumulate(equity_curve)

drawdown = (equity_curve - peak) / peak

fig = make_subplots(
    rows=5, cols=1,
    shared_xaxes=True,
    vertical_spacing=0.02,
    row_heights=[0.35, 0.15, 0.15, 0.15, 0.2]
)

fig.add_trace(go.Scatter(
    x=df.index,
    y=drawdown,
    name="Drawdown",
    fill='tozeroy'
), row=5, col=1)

max_dd = np.min(drawdown)
print("Max Drawdown:", max_dd)

fig.add_hline(
    y=max_dd,
    line_dash="dash",
    row=5, col=1
)

fig.add_trace(go.Scatter(
    x=df.index,
    y=drawdown,
    fill='tozeroy',
    mode='lines',
    name="Drawdown"
), row=5, col=1)

"""# ORDER BOOK PROJECT"""

transaction_cost = 0.001

equity = 1
position = 0
transaction_cost = 0.001

for i in range(1, len(returns)):

    signal = signals[i]

    prev_position = position

    if signal == 1:
        position = 1
    elif signal == -1:
        position = 0

    position_change = abs(position - prev_position)


    cost = transaction_cost * position_change
    equity *= (1 - cost)


    equity *= (1 + position * returns[i])

cost = transaction_cost * abs(position_change)
equity *= (1 - cost)

slippage = 0.0005

slippage = 0.0005

for i in range(1, len(returns)):

    price_return = returns[i]

    execution_cost = slippage
    equity *= (1 - execution_cost)
    equity *= (1 + position * price_return)

equity = 1
position = 0

transaction_cost = 0.001   # 0.1%
slippage = 0.0005          # 5 bps

for i in range(1, len(returns)):

    signal = signals[i]

    prev_position = position

    # update position
    if signal == 1:
        position = 1
    elif signal == -1:
        position = 0

    # 🔥 trade happened?
    position_change = abs(position - prev_position)

    # cost (transaction + slippage)
    cost = (transaction_cost + slippage) * position_change
    equity *= (1 - cost)

    # apply market return
    equity *= (1 + position * returns[i])

"""# SENTIMENT ANALYSIS"""

import yfinance as yf

ticker = yf.Ticker("RELIANCE.NS")
news = ticker.news

pip install transformers

from transformers import pipeline

sentiment_model = pipeline("sentiment-analysis") ######## THIS IS THE NLP STEP TOKENIZATION ,EMBEDDDING ,TRANSFORMER ENCODING,CLASSIFICATIONam

print(news[0])

sentiments = []

for item in news:
    try:
        text = item['content']['title']   # ✅ correct path
    except:
        continue

    result = sentiment_model(text)[0]

    score = result['score']
    label = result['label']

    if label == "POSITIVE":
        sentiments.append(score)
    else:
        sentiments.append(-score)

daily_sentiment = np.mean(sentiments)

sentiment_score = pd.Series(sentiments).rolling(5).mean()

sentiments = []
news_dates = []

for item in news:

    try:
        text = item['content']['title']
    except:
        continue

    result = sentiment_model(text)[0]

    score = result['score']
    label = result['label']

    sentiment = score if label == "POSITIVE" else -score

    sentiments.append(sentiment)

    try:
        timestamp = item['content']['pubDate']
    except:
        timestamp = None

    news_dates.append(timestamp)

import pandas as pd

sent_df = pd.DataFrame({
    "date": news_dates,
    "sentiment": sentiments
})

sent_df.dropna(inplace=True)

sent_df['date'] = pd.to_datetime(sent_df['date'], errors='coerce')
sent_df.dropna(inplace=True)

news_dates.append(pd.Timestamp.today())

"""## ADVANCED NLP FinBERT"""

pip install transformers torch

from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import pipeline

model_name = "ProsusAI/finbert"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

finbert = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer)

from transformers import pipeline

finbert = pipeline("sentiment-analysis", model="ProsusAI/finbert")

print(finbert("Reliance stocks are rising after strong earnings"))

"""# MERGING FinBERT AND NIFTY"""

import yfinance as yf
import pandas as pd
import numpy as np

data = yf.download("^NSEI", start="2018-01-01")

data = data[['Close']].dropna()
data['returns'] = data['Close'].pct_change().fillna(0)

from transformers import pipeline

finbert = pipeline("sentiment-analysis", model="ProsusAI/finbert")

news_texts = [
    "Market rallies after strong earnings",
    "Inflation fears drag market down",
    "NIFTY shows stable movement"
]

################## RUN FinBERT


sentiments = []

for text in news_texts:
    result = finbert(text)[0]

    if result['label'].lower() == "positive":
        sentiments.append(result['score'])
    elif result['label'].lower() == "negative":
        sentiments.append(-result['score'])
    else:
        sentiments.append(0)

sent_series = pd.Series(sentiments)
daily_sentiment = sent_series.mean()

data['sentiment'] = daily_sentiment

data['sentiment'] = data['sentiment'].fillna(method='ffill')

data['signal'] = 0

data['signal'] = np.where(
    (data['returns'] > 0) & (data['sentiment'] > 0),
    1,
    np.where(
        (data['returns'] < 0) & (data['sentiment'] < 0),
        -1,
        0
    )
)

equity = 1
position = 0

for i in range(1, len(data)):

    signal = data['signal'].iloc[i]
    ret = data['returns'].iloc[i]

    if signal == 1:
        position = 1
    elif signal == -1:
        position = 0

    equity *= (1 + position * ret)

print("Final Equity:", equity)

equity_curve = (1 + data['returns']).cumprod()
strategy_curve = equity  # replace with list if looped properly

import matplotlib.pyplot as plt

plt.figure(figsize=(12,5))
plt.plot(equity_curve, label="Buy & Hold")
plt.plot(strategy_curve, label="Sentiment Strategy")
plt.legend()
plt.grid()
plt.show()

import matplotlib.pyplot as plt

fig, axs = plt.subplots(3, 1, figsize=(14,10), sharex=True)

# --- Price ---
axs[0].plot(data['Close'], label="NIFTY Price", color="blue")
axs[0].set_title("NIFTY Price")
axs[0].legend()
axs[0].grid()

# --- Sentiment ---
axs[1].plot(data['sentiment'], label="FinBERT Sentiment", color="purple")
axs[1].axhline(0, color='black', linestyle='--', linewidth=1)
axs[1].set_title("News Sentiment (FinBERT)")
axs[1].legend()
axs[1].grid()

# --- Signal ---
axs[2].plot(data['signal'], label="Trading Signal", color="green")
axs[2].axhline(0, color='black', linestyle='--', linewidth=1)
axs[2].set_title("Trading Signals")
axs[2].legend()
axs[2].grid()

plt.tight_layout()
plt.show()

plt.figure(figsize=(14,5))

plt.plot(data['Close'].pct_change().cumsum(), label="Buy & Hold", alpha=0.7)
plt.plot(data['signal'].cumsum(), label="Strategy Signal", alpha=0.7)

plt.title("Strategy vs Market Performance")
plt.legend()
plt.grid()
plt.show()

plt.figure(figsize=(14,6))

plt.plot(data['Close'], label="NIFTY Price", alpha=0.7)

buy = data[data['signal'] == 1]
sell = data[data['signal'] == -1]

plt.scatter(buy.index, buy['Close'], marker="^", color="green", label="BUY", s=80)
plt.scatter(sell.index, sell['Close'], marker="v", color="red", label="SELL", s=80)

plt.title("Trade Signals on NIFTY")
plt.legend()
plt.grid()
plt.show()

rolling_return = data['signal'] * data['returns']
rolling_sharpe = rolling_return.rolling(20).mean() / (rolling_return.rolling(20).std() + 1e-8)

plt.figure(figsize=(14,4))
plt.plot(rolling_sharpe, label="Rolling Sharpe")
plt.axhline(0, color='black', linestyle='--')
plt.title("Strategy Stability Over Time")
plt.legend()
plt.grid()
plt.show()

fig, ax1 = plt.subplots(figsize=(14,5))

ax1.plot(data['Close'], color="blue", label="Price")
ax2 = ax1.twinx()

ax2.plot(data['sentiment'], color="yellow", alpha=0.5, label="Sentiment")

ax1.set_title("Price vs FinBERT Sentiment")
ax1.grid()

fig.legend()
plt.show()

"""# PLOTLY IINTERACTIVE DASHBOARD"""

import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=data.index,
    y=data['Close'],
    mode='lines',
    name='NIFTY Price'
))

fig.update_layout(
    title="NIFTY Interactive Price Chart",
    xaxis_title="Date",
    yaxis_title="Price",
    template="plotly_dark"
)

fig.show()

buy = data[data['signal'] == 1]
sell = data[data['signal'] == -1]

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=data.index,
    y=data['Close'],
    mode='lines',
    name='Price'
))

fig.add_trace(go.Scatter(
    x=buy.index,
    y=buy['Close'],
    mode='markers',
    name='BUY',
    marker=dict(color='green', size=10, symbol='triangle-up')
))

fig.add_trace(go.Scatter(
    x=sell.index,
    y=sell['Close'],
    mode='markers',
    name='SELL',
    marker=dict(color='red', size=10, symbol='triangle-down')
))

fig.update_layout(
    title="Trading Signals on NIFTY",
    template="plotly_dark"
)

fig.show()

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=data.index,
    y=data['Close'],
    name='Price',
    yaxis='y1'
))

fig.add_trace(go.Scatter(
    x=data.index,
    y=data['sentiment'],
    name='FinBERT Sentiment',
    yaxis='y2',
    opacity=0.6
))

fig.update_layout(
    title="Price vs Sentiment",
    yaxis=dict(title="Price"),
    yaxis2=dict(
        title="Sentiment",
        overlaying="y",
        side="right"
    ),
    template="plotly_dark"
)

fig.show()

equity = (1 + data['returns']).cumprod()

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=data.index,
    y=equity,
    mode='lines',
    name='Buy & Hold'
))

fig.update_layout(
    title="Equity Curve (Benchmark: NIFTY)",
    template="plotly_dark"
)

fig.show()

"""# REAL-TIME STREAMING UPDATES"""

import plotly.graph_objects as go
import time
import numpy as np

prices = data['Close'].values[:200]

fig = go.FigureWidget()

line = fig.add_scatter(y=[], mode='lines', name='Price')

fig.update_layout(
    title="Live NIFTY Streaming Chart",
    template="plotly_dark"
)

fig

live_prices = []

for i in range(len(prices)):

    new_price = prices[i]
    live_prices.append(new_price)


    with fig.batch_update():
        fig.data[0].y = live_prices

    time.sleep(0.1)

sentiment_stream = np.random.normal(0, 0.5, len(prices))

fig.add_scatter(y=[], mode='lines', name='Sentiment', yaxis='y2')

fig.update_layout(
    yaxis2=dict(overlaying='y', side='right')
)

sent_list = []

for i in range(len(prices)):

    live_prices.append(prices[i])
    sent_list.append(sentiment_stream[i])

    with fig.batch_update():
        fig.data[0].y = live_prices
        fig.data[1].y = sent_list

    time.sleep(0.1)

"""# ⏹ HYPER-PARAMETER TUNING"""

!pip install optuna

import optuna
import numpy as np

def objective(trial):

    hidden = trial.suggest_int("hidden", 32, 256)
    dropout = trial.suggest_float("dropout", 0.1, 0.5)
    lr = trial.suggest_float("lr", 1e-4, 1e-2, log=True)

    model = build_lstm(hidden, dropout)

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=lr),
        loss="mse"
    )

    model.fit(X_train, y_train,
              epochs=5,
              batch_size=32,
              verbose=0)

    pred = model.predict(X_val)

    loss = np.mean((y_val - pred) ** 2)

    return loss

import optuna
import tensorflow as tf
from tensorflow.keras import layers
import numpy as np

def build_lstm(hidden_units, dropout_rate, input_shape):

    model = tf.keras.Sequential()

    model.add(layers.LSTM(hidden_units, return_sequences=False, input_shape=input_shape))
    model.add(layers.Dropout(dropout_rate))

    model.add(layers.Dense(1))

    return model

def objective(trial):

    hidden = trial.suggest_int("hidden", 32, 256)
    dropout = trial.suggest_float("dropout", 0.1, 0.5)
    lr = trial.suggest_float("lr", 1e-4, 1e-2, log=True)

    model = build_lstm(hidden, dropout, X_train.shape[1:])

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=lr),
        loss="mse"
    )

    model.fit(
        X_train, y_train,
        epochs=5,
        batch_size=32,
        verbose=0
    )

    pred = model.predict(X_val)

    loss = np.mean((y_val - pred) ** 2)

    return loss

split = int(len(X) * 0.8)

X_train = X[:split]
X_val = X[split:]

y_train = y[:split]
y_val = y[split:]

print(X.shape)

def create_sequences(X, y, window=10):

    Xs, ys = [], []

    for i in range(len(X) - window):

        Xs.append(X[i:i+window])
        ys.append(y[i+window])

    return np.array(Xs), np.array(ys)

X_seq, y_seq = create_sequences(X, y, window=10)

print(type(X))
print(type(y))

X = np.array(X)
y = np.array(y)

X_seq, y_seq = create_sequences(X, y, window=10)

split = int(len(X_seq) * 0.8)

X_train, X_val = X_seq[:split], X_seq[split:]
y_train, y_val = y_seq[:split], y_seq[split:]

print(X_train.shape)
print(X_val.shape)

import tensorflow as tf
from tensorflow.keras import layers, Input

def build_lstm(hidden, dropout, input_shape):

    model = tf.keras.Sequential([
        Input(shape=input_shape),
        layers.LSTM(hidden),
        layers.Dropout(dropout),
        layers.Dense(1)
    ])

    return model

print(X_train.shape)

X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], -1)
X_val = X_val.reshape(X_val.shape[0], X_val.shape[1], -1)

X.shape = (samples, features)